// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  type BinaryReader,
  type BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  deepEqual,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
} from '@clockworklabs/spacetimedb-sdk';

import { TransactionType as __TransactionType } from './transaction_type_type';

export type CreateTransaction = {
  stockId: number;
  amount: bigint;
  txType: __TransactionType;
};

/**
 * A namespace for generated helper functions.
 */
export namespace CreateTransaction {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('stockId', AlgebraicType.createU16Type()),
      new ProductTypeElement('amount', AlgebraicType.createU64Type()),
      new ProductTypeElement(
        'txType',
        __TransactionType.getTypeScriptAlgebraicType()
      ),
    ]);
  }

  export function serialize(
    writer: BinaryWriter,
    value: CreateTransaction
  ): void {
    CreateTransaction.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): CreateTransaction {
    return CreateTransaction.getTypeScriptAlgebraicType().deserialize(reader);
  }
}
