// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";

// Import and reexport all reducer arg types
import { AddUpgrade } from "./add_upgrade_reducer.ts";
export { AddUpgrade };
import { BuyUpgrade } from "./buy_upgrade_reducer.ts";
export { BuyUpgrade };
import { IdentityConnected } from "./identity_connected_reducer.ts";
export { IdentityConnected };
import { IdentityDisconnected } from "./identity_disconnected_reducer.ts";
export { IdentityDisconnected };
import { IncreaseMoney } from "./increase_money_reducer.ts";
export { IncreaseMoney };
import { SetName } from "./set_name_reducer.ts";
export { SetName };

// Import and reexport all table handle types
import { PlayerTableHandle } from "./player_table.ts";
export { PlayerTableHandle };
import { UpgradesTableHandle } from "./upgrades_table.ts";
export { UpgradesTableHandle };

// Import and reexport all types
import { Player } from "./player_type.ts";
export { Player };
import { Upgrades } from "./upgrades_type.ts";
export { Upgrades };

const REMOTE_MODULE = {
  tables: {
    player: {
      tableName: "player",
      rowType: Player.getTypeScriptAlgebraicType(),
      primaryKey: "identity",
    },
    upgrades: {
      tableName: "upgrades",
      rowType: Upgrades.getTypeScriptAlgebraicType(),
      primaryKey: "id",
    },
  },
  reducers: {
    add_upgrade: {
      reducerName: "add_upgrade",
      argsType: AddUpgrade.getTypeScriptAlgebraicType(),
    },
    buy_upgrade: {
      reducerName: "buy_upgrade",
      argsType: BuyUpgrade.getTypeScriptAlgebraicType(),
    },
    identity_connected: {
      reducerName: "identity_connected",
      argsType: IdentityConnected.getTypeScriptAlgebraicType(),
    },
    identity_disconnected: {
      reducerName: "identity_disconnected",
      argsType: IdentityDisconnected.getTypeScriptAlgebraicType(),
    },
    increase_money: {
      reducerName: "increase_money",
      argsType: IncreaseMoney.getTypeScriptAlgebraicType(),
    },
    set_name: {
      reducerName: "set_name",
      argsType: SetName.getTypeScriptAlgebraicType(),
    },
  },
  // Constructors which are used by the DbConnectionImpl to
  // extract type information from the generated RemoteModule.
  //
  // NOTE: This is not strictly necessary for `eventContextConstructor` because
  // all we do is build a TypeScript object which we could have done inside the
  // SDK, but if in the future we wanted to create a class this would be
  // necessary because classes have methods, so we'll keep it.
  eventContextConstructor: (imp: DbConnectionImpl, event: Event<Reducer>) => {
    return {
      ...(imp as DbConnection),
      event
    }
  },
  dbViewConstructor: (imp: DbConnectionImpl) => {
    return new RemoteTables(imp);
  },
  reducersConstructor: (imp: DbConnectionImpl, setReducerFlags: SetReducerFlags) => {
    return new RemoteReducers(imp, setReducerFlags);
  },
  setReducerFlagsConstructor: () => {
    return new SetReducerFlags();
  }
}

// A type representing all the possible variants of a reducer.
export type Reducer = never
| { name: "AddUpgrade", args: AddUpgrade }
| { name: "BuyUpgrade", args: BuyUpgrade }
| { name: "IdentityConnected", args: IdentityConnected }
| { name: "IdentityDisconnected", args: IdentityDisconnected }
| { name: "IncreaseMoney", args: IncreaseMoney }
| { name: "SetName", args: SetName }
;

export class RemoteReducers {
  constructor(private connection: DbConnectionImpl, private setCallReducerFlags: SetReducerFlags) {}

  addUpgrade(identifier: string, title: string, description: string, level: number, cost: bigint, passiveIncomeBonus: bigint | undefined, clickPowerBonus: bigint | undefined, clickTimerBonus: bigint | undefined, autoClickRate: bigint | undefined) {
    const __args = { identifier, title, description, level, cost, passiveIncomeBonus, clickPowerBonus, clickTimerBonus, autoClickRate };
    let __writer = new BinaryWriter(1024);
    AddUpgrade.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("add_upgrade", __argsBuffer, this.setCallReducerFlags.addUpgradeFlags);
  }

  onAddUpgrade(callback: (ctx: ReducerEventContext, identifier: string, title: string, description: string, level: number, cost: bigint, passiveIncomeBonus: bigint | undefined, clickPowerBonus: bigint | undefined, clickTimerBonus: bigint | undefined, autoClickRate: bigint | undefined) => void) {
    this.connection.onReducer("add_upgrade", callback);
  }

  removeOnAddUpgrade(callback: (ctx: ReducerEventContext, identifier: string, title: string, description: string, level: number, cost: bigint, passiveIncomeBonus: bigint | undefined, clickPowerBonus: bigint | undefined, clickTimerBonus: bigint | undefined, autoClickRate: bigint | undefined) => void) {
    this.connection.offReducer("add_upgrade", callback);
  }

  buyUpgrade(upgradeId: number) {
    const __args = { upgradeId };
    let __writer = new BinaryWriter(1024);
    BuyUpgrade.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("buy_upgrade", __argsBuffer, this.setCallReducerFlags.buyUpgradeFlags);
  }

  onBuyUpgrade(callback: (ctx: ReducerEventContext, upgradeId: number) => void) {
    this.connection.onReducer("buy_upgrade", callback);
  }

  removeOnBuyUpgrade(callback: (ctx: ReducerEventContext, upgradeId: number) => void) {
    this.connection.offReducer("buy_upgrade", callback);
  }

  onIdentityConnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("identity_connected", callback);
  }

  removeOnIdentityConnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("identity_connected", callback);
  }

  onIdentityDisconnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("identity_disconnected", callback);
  }

  removeOnIdentityDisconnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("identity_disconnected", callback);
  }

  increaseMoney() {
    this.connection.callReducer("increase_money", new Uint8Array(0), this.setCallReducerFlags.increaseMoneyFlags);
  }

  onIncreaseMoney(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("increase_money", callback);
  }

  removeOnIncreaseMoney(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("increase_money", callback);
  }

  setName(username: string) {
    const __args = { username };
    let __writer = new BinaryWriter(1024);
    SetName.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("set_name", __argsBuffer, this.setCallReducerFlags.setNameFlags);
  }

  onSetName(callback: (ctx: ReducerEventContext, username: string) => void) {
    this.connection.onReducer("set_name", callback);
  }

  removeOnSetName(callback: (ctx: ReducerEventContext, username: string) => void) {
    this.connection.offReducer("set_name", callback);
  }

}

export class SetReducerFlags {
  addUpgradeFlags: CallReducerFlags = 'FullUpdate';
  addUpgrade(flags: CallReducerFlags) {
    this.addUpgradeFlags = flags;
  }

  buyUpgradeFlags: CallReducerFlags = 'FullUpdate';
  buyUpgrade(flags: CallReducerFlags) {
    this.buyUpgradeFlags = flags;
  }

  increaseMoneyFlags: CallReducerFlags = 'FullUpdate';
  increaseMoney(flags: CallReducerFlags) {
    this.increaseMoneyFlags = flags;
  }

  setNameFlags: CallReducerFlags = 'FullUpdate';
  setName(flags: CallReducerFlags) {
    this.setNameFlags = flags;
  }

}

export class RemoteTables {
  constructor(private connection: DbConnectionImpl) {}

  get player(): PlayerTableHandle {
    return new PlayerTableHandle(this.connection.clientCache.getOrCreateTable<Player>(REMOTE_MODULE.tables.player));
  }

  get upgrades(): UpgradesTableHandle {
    return new UpgradesTableHandle(this.connection.clientCache.getOrCreateTable<Upgrades>(REMOTE_MODULE.tables.upgrades));
  }
}

export class SubscriptionBuilder extends SubscriptionBuilderImpl<RemoteTables, RemoteReducers, SetReducerFlags> { }

export class DbConnection extends DbConnectionImpl<RemoteTables, RemoteReducers, SetReducerFlags> {
  static builder = (): DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext> => {
    return new DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext>(REMOTE_MODULE, (imp: DbConnectionImpl) => imp as DbConnection);
  }
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  }
}

export type EventContext = EventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type ReducerEventContext = ReducerEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type SubscriptionEventContext = SubscriptionEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
export type ErrorContext = ErrorContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
