// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
export type Upgrades = {
  id: number,
  level: number,
  cost: bigint,
  title: string,
  identifier: string,
  description: string,
  passiveIncomeBonus: bigint | undefined,
  clickPowerBonus: bigint | undefined,
  clickTimerBonus: bigint | undefined,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Upgrades {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createU16Type()),
      new ProductTypeElement("level", AlgebraicType.createU8Type()),
      new ProductTypeElement("cost", AlgebraicType.createU128Type()),
      new ProductTypeElement("title", AlgebraicType.createStringType()),
      new ProductTypeElement("identifier", AlgebraicType.createStringType()),
      new ProductTypeElement("description", AlgebraicType.createStringType()),
      new ProductTypeElement("passiveIncomeBonus", AlgebraicType.createOptionType(AlgebraicType.createU128Type())),
      new ProductTypeElement("clickPowerBonus", AlgebraicType.createOptionType(AlgebraicType.createU128Type())),
      new ProductTypeElement("clickTimerBonus", AlgebraicType.createOptionType(AlgebraicType.createU64Type())),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Upgrades): void {
    Upgrades.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Upgrades {
    return Upgrades.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


