/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UpgradesImport } from './routes/upgrades'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const UpgradesRoute = UpgradesImport.update({
  id: '/upgrades',
  path: '/upgrades',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/upgrades': {
      id: '/upgrades'
      path: '/upgrades'
      fullPath: '/upgrades'
      preLoaderRoute: typeof UpgradesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/upgrades': typeof UpgradesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/upgrades': typeof UpgradesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/upgrades': typeof UpgradesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/upgrades'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/upgrades'
  id: '__root__' | '/' | '/upgrades'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UpgradesRoute: typeof UpgradesRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UpgradesRoute: UpgradesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/upgrades"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/upgrades": {
      "filePath": "upgrades.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
